# Generated by Django 3.0.3 on 2020-03-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='docfile',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
